name: 'in_tallinn_content'
version: 0.0.2
publish_to: none
description: Content for inTallinn.ee
author: Mike Hoolehan <mike@hoolehan.com>
homepage: https://intallinn.ee
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  barback: ">=0.15.2+4"
  markdown: ">=0.9.0"
  mustache_no_mirror: ">=0.1.8"
  dart_to_js_script_rewriter: '^1.0.1'
dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  yaml: '^2.1.0'
transformers:
- dart_to_js_script_rewriter
- in_tallinn_content/transformer/md_to_html_transformer:
    template: "web/content/section/template.html"
